services:
  postgres:
    image: postgres
  mongodb:
    image: mongo
  # auctionservice:
  #   image: ${DOCKER_REGISTRY-}auctionservice
  #   build:
  #     context: .
  #     dockerfile: src/AuctionService/Dockerfile
